name: Mover a "En progreso" cuando se asigna

on:
  issues:
    types:
      - assigned

jobs:
  mover-a-progreso:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar token para autenticación
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Token configurado."

      - name: Mover ítem a la columna "En progreso"
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/davidh-7/InfoMates/projects/columns/cards \
            -d '{
              "content_type": "Issue",
              "content_id": "${{ github.event.issue.id }}",
              "column_name": "En progreso"
            }'
